### PR TITLE
File Creator Dockerfile and .yml for CI/CD

### PR DESCRIPTION
**Pull request by mik-tf**
This is a PR to incorporate the Dockerfile and .yml file for the [file_creator.v](https://github.com/threefoldtech/farmerbot/blob/development/scripts/file_creator.v) program.

The publish.yml should be updated to take into account the other Dockerfile in the repository (for file_creator.v).

I propose to use a [matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) in publish.yml.

I am not sure of the final version of the publish.yml with the matrix, so I will post it here (next comment) and we can discuss how to improve it, if needed.
Note that this is a draft PR as it is not yet ready for merge.

@brandonpille 
If you can have a look, it would be great! Thanks.

### CODE REVIEW

**Comment by mik-tf** [comment]
publish.yml could be edited with the following matrix strategy. It might need some improvements.

```
name: Publish 

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - dockerfile: ./Dockerfile
            image: ghcr.io/${{ github.repository }}/farmerbot_image
          - dockerfile: ./file_creator/Dockerfile
            image: ghcr.io/${{ github.repository }}/file_creator_image
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

**Comment by brandonpille** [comment]
Oh that's a great idea! You can go ahead and do the implementation in this PR.

**Review by brandonpille — APPROVED** [review]
Looks good!

**Comment by Mik-TF** [comment]
If this doesn't work, perhaps we'll need to change the line:

> ./Dockerfile
> ./file_creator/Dockerfile
to this
> ./src/Dockerfile
> ./src/file_creator/Dockerfile

This is taken from [this issue](https://github.com/docker/build-push-action/issues/561#issuecomment-1054596444).

**Pull request merged**
